export const userListNewbiesData = [
    {
        id: 123456,
        username: 'KätzchenFreundin',
        gender: 'female',
        userIsLoggedIn: true,
        registeredSince: 'vor 5 min',
        //userProfilePath: 'user/123456/kaetzchenfreundin',
        userProfilePath: '/user',
        userAvatarPathSmall: '/img/user-pictures/123456/avatar_small_20220410.png',
    },
    {
        id: 654322,
        username: 'pussyHunter',
        gender: 'male',
        userIsLoggedIn: true,
        registeredSince: 'vor 21 min',
        //userProfilePath: 'user/654322/pussyhunter',
        userProfilePath: '/user',
        userAvatarPathSmall: '/img/user-pictures/default/avatar_small_m.png',
    },
    {
        id: 987654,
        username: 'AlienFighter',
        gender: 'diverse',
        userIsLoggedIn: false,
        registeredSince: 'vor 33 min',
        userProfilePath: 'user/987654/alienfighter',
        userAvatarPathSmall: '/img/user-pictures/default/avatar_small_d.png',
    },
    {
        id: 765498,
        username: 'DarkAngel~666~',
        gender: 'female',
        userIsLoggedIn: true,
        registeredSince: 'vor 1 std',
        //userProfilePath: 'user/765498/darkangel-666-',
        userProfilePath: '/user',
        userAvatarPathSmall: '/img/user-pictures/default/avatar_small_f.png',
    },
    {
        id: 300111,
        username: 'GoldenBoyInReal',
        gender: 'male',
        userIsLoggedIn: false,
        //userProfilePath: 'user/300111/goldenboyinreal',
        userProfilePath: '/user',
        registeredSince: 'vor 4 std',
    },
    {
        id: 363636,
        username: 'EinhornMensch',
        gender: 'diverse',
        userIsLoggedIn: true,
        registeredSince: 'vor 11 std',
        //userProfilePath: 'user/363636/einhornmensch',
        userProfilePath: '/user',
        userAvatarPathSmall: '/img/user-pictures/default/avatar_small_d.png',
    },
];
