export const userListNewbiesData = [
    {
        id: 123456,
        username: 'KätzchenFreundin',
        gender: 'female',
        status: 'online',
        registerTime: 'vor 5 min',
        //userLink: 'user/123456/kaetzchenfreundin',
        userLink: '/user',
        image: '/img/user-pictures/123456/avatar_small_20220410.png',
    },
    {
        id: 654322,
        username: 'pussyHunter',
        gender: 'male',
        status: 'online',
        registerTime: 'vor 21 min',
        //userLink: 'user/654322/pussyhunter',
        userLink: '/user',
        image: '/img/user-pictures/default/avatar_small_m.png',
    },
    {
        id: 987654,
        username: 'AlienFighter',
        gender: 'diverse',
        status: 'online',
        registerTime: 'vor 33 min',
        userLink: 'user/987654/alienfighter',
        image: '/img/user-pictures/default/avatar_small_d.png',
    },
    {
        id: 765498,
        username: 'DarkAngel~666~',
        gender: 'female',
        status: 'offline',
        registerTime: 'vor 1 std',
        //userLink: 'user/765498/darkangel-666-',
        userLink: '/user',
        image: '/img/user-pictures/default/avatar_small_f.png',
    },
    {
        id: 300111,
        username: 'GoldenBoyInReal',
        gender: 'male',
        status: 'offline',
        //userLink: 'user/300111/goldenboyinreal',
        userLink: '/user',
        registerTime: 'vor 4 std',
    },
    {
        id: 363636,
        username: 'EinhornMensch',
        gender: 'diverse',
        status: 'offline',
        registerTime: 'vor 11 std',
        //userLink: 'user/363636/einhornmensch',
        userLink: '/user',
        image: '/img/user-pictures/default/avatar_small_d.png',
    },
];
