export const chatRoomsOverviewData = {
    roomsCurrentVisitorsTotal: 1,
    rooms: [
        {
            id: 0,
            title: 'ANIME_TITLE',
            description: 'ANIME_DESCRIPTION',
            category: 'nerd',
            tags: ['anime', 'manga', 'japan', 'comic', 'nerd', 'fantasy'],
            roomAvatarPath: 'path/image.webp',
            roomPath: '/chatrooms/anime',
            currentVisitors: 2,
        },
        {
            id: 1,
            title: 'BOOKS_TITLE',
            description: 'BOOKS_DESCRIPTION',
            category: 'fantasy',
            tags: ['introvert', 'fantasy', 'science', 'manga'],
            roomAvatarPath: 'path/image.webp',
            roomPath: '',
            currentVisitors: 0,
        },
        {
            id: 2,
            title: 'COSPLAY_TITLE',
            description: 'COSPLAY_DESCRIPTION',
            category: 'nerd',
            tags: ['anime', 'manga', 'videogame', 'nerd', 'art', 'diy', 'clothing', 'extrovert'],
            roomAvatarPath: 'path/image.webp',
            roomPath: '',
            currentVisitors: 0,
        },
        {
            id: 3,
            title: 'GAMING_TITLE',
            description: 'GAMING_DESCRIPTION',
            category: 'nerd',
            tags: ['videogame', 'computer', 'introvert', 'fantasy', 'nerd'],
            roomAvatarPath: 'path/image.webp',
            roomPath: '',
            currentVisitors: 0,
        },
        {
            id: 4,
            title: 'FITNESS_TITLE',
            description: 'FITNESS_DESCRIPTION',
            category: 'sporty-healthy',
            tags: ['sport', 'health'],
            roomAvatarPath: 'path/image.webp',
            roomPath: '',
            currentVisitors: 0,
        },
        {
            id: 5,
            title: 'PHOTOGRAPHY_TITLE',
            description: 'PHOTOGRAPHY_DESCRIPTION',
            category: 'art',
            tags: ['art', 'hobby', 'clothing'],
            roomAvatarPath: 'path/image.webp',
            roomPath: '',
            currentVisitors: 0,
        },
        {
            id: 6,
            title: 'VEGAN_TITLE',
            description: 'VEGAN_DESCRIPTION',
            category: 'sporty-healthy',
            tags: ['food', 'health', 'nourishment', 'nature', 'idealist'],
            roomAvatarPath: 'path/image.webp',
            roomPath: '',
            currentVisitors: 0,
        },
    ],
    categories: [
        'sporty-healthy',
        'arts-crafts',
        'economy-politics-money',
        'music',
        'bauty',
        'religion-ethics',
        'technologies',
        'nature-plants',
        'animals',
        'videogames-mediaconsumption',
    ],
    tags: [
        'japan',
        'comic',
        'nerd',
        'fantasy',
        'introvert',
        'science',
        'anime',
        'manga',
        'videogame',
        'art',
        'diy',
        'clothing',
        'extrovert',
        'computer',
        'sport',
        'health',
        'hobby',
        'food',
        'nourishment',
        'nature',
        'idealist',
    ],
};
